// <auto-generated />
namespace WM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddProizvodac : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProizvodac));
        
        string IMigrationMetadata.Id
        {
            get { return "202012101323588_AddProizvodac"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
